### ISSUE TITLE
[api-mock] Dont make changes if put/post/etc returns a HttpErrorResponse

### ISSUE THREAD

**Issue by yusijs** [KostyaTretyak/ng-stack#100]
I'm currently using api-mock for a project, and I've found a lot of stuff I absolutely love about it. However, I recently implemented a PUT operation where I want it to throw errors in certain scenarioes. I implemented a handler for it, and I am able to return an error. 

Despite returning an error, the items in my collections gets updated. Any chance this behaviour can be changed, or we can somehow control the updates ourselves with a config flag?

Thanks!

**Comment by KostyaTretyak** [comment]
Do you use [responseCallback](https://github.com/KostyaTretyak/ng-stack/blob/master/projects/api-mock/README.md#responsecallback) in this case?

**Comment by yusijs** [comment]
I do, yes.

**Comment by KostyaTretyak** [comment]
That is, your Angular component gets an error, but `@ng-stack/api-mock` still updates the mock data?

**Comment by yusijs** [comment]
Yes - the 400 errors gets returned as expected, but the item still gets changed.

**Comment by KostyaTretyak** [comment]
Sorry, but `@ng-stack/api-mock` no more supports.
