### ISSUE TITLE
Class constructor FormControl cannot be invoked without 'new'

### ISSUE THREAD

**Issue by GeorgeKnap** [KostyaTretyak/ng-stack#107]
When testing a component that uses FormControl from @ng-stack/forms  I'm getting following error
[reproduced in this repo](https://github.com/GeorgeKnap/jest-ng-stack-forms-error/tree/master/jest-error-repo)
When used with FormControl from @angular/forms the error is gone.

```
C:\development\jest-ng-stack-forms-error\jest-error-repo>nx test test-this-lib

> nx run test-this-lib:test

 FAIL   test-this-lib  libs/test-this-lib/src/lib/test-this-component/test-this-component.component.spec.ts
  TestThisComponentComponent
    × should create (27 ms)

  ● TestThisComponentComponent › should create

    TypeError: Class constructor FormControl cannot be invoked without 'new'

       8 | })
       9 | export class TestThisComponentComponent {
    > 10 |   control = new FormControl<string>('init value');
         |             ^
      11 | }
      12 |

      at new FormControl (../../node_modules/projects/forms/src/lib/form-control.ts:42:5)
      at new TestThisComponentComponent (src/lib/test-this-component/test-this-component.component.ts:10:13)
      at NodeInjectorFactory.TestThisComponentComponent_Factory [as factory] (..\..\ng:\TestThisComponentComponent\ɵfac.js:5:10)
      at src/lib/test-this-component/test-this-component.component.spec.ts:17:23

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.362 s
Ran all test suites.
```

**Comment by KostyaTretyak** [comment]
Hi, @GeorgeKnap. Please, provide a link to the stackblitz that reproduces the bug. Try to write an example where there are no third-party utilities, such as nx.

**Comment by KostyaTretyak** [comment]
After a quick look at your repository, I noticed that you are not importing the `NgStackFormsModule` into the [test module](https://github.com/GeorgeKnap/jest-ng-stack-forms-error/blob/fa0036bbdc7f9c01294d9d0c89d805e163764f01/jest-error-repo/libs/test-this-lib/src/lib/test-this-component/test-this-component.component.spec.ts#L10-L12). Try import it, the issue may disappear.

**Comment by GeorgeKnap** [comment]
@KostyaTretyak  I tried to import the `NgStackFormModule`  but getting another error: 
![image](https://user-images.githubusercontent.com/11920691/151941714-18c6dca3-076b-42aa-902d-f009cfab1e72.png)

**Comment by KostyaTretyak** [comment]
This error is issued by jest, not karma. Try karma.

**Comment by GeorgeKnap** [comment]
> This error is issued by jest, not karma. Try karma.

NX monorepo is using Jest.  In Karma it works. 
I have a ticket open in Jest repo in case it's Jest's issue https://github.com/facebook/jest/issues/12282

**Comment by KostyaTretyak** [comment]
Understand. If this works with karma, then I'm closing this issue. It is not easy to integrate jest into the Angular project. You may not have made all the necessary settings.

**Comment by GeorgeKnap** [comment]
Minimal repo Angular 13+Jest+@ng-stack/forms [here](https://github.com/GeorgeKnap/angular-jest-ng-stack-forms)
[StackOverflow ticket here](https://stackoverflow.com/questions/71036096/class-constructor-formcontrol-cannot-be-invoked-without-new)
