### ISSUE TITLE
@ng-stack/contenteditable - Space Problem (Firefox only)

### ISSUE THREAD

**Issue by frontdevss** [KostyaTretyak/ng-stack#108]
I'm currently using @ng-stack/contenteditable for a project, and I've found a issue that is happening in Firefox. 

Reproduction step:
- click the mouse cursor before the first word
- press space two times
- it set the second space automatically behind the First word (and it set the cursor behind the First word)

Expected behaviour:
- typing in front of a word doesn't jump over it.

**Comment by KostyaTretyak** [comment]
@frontdevss, please provide link to https://stackblitz.com/ where I can see the issue.
