### ISSUE TITLE
Is this deprecated with Angular 14?

### ISSUE THREAD

**Issue by iliakan** [KostyaTretyak/ng-stack#112]
Hi,

As there're [Typed Forms](https://angular.io/guide/typed-forms) in Angular 14, is @ng-stack/forms library still actual?

Sorry, I don't know much about it, just got a project to upgrade Angular 13 → 14, and it uses @ng-stack/forms, so I wonder whether to work to replace @ng-stack/forms with Angular Typed Forms, or not?

P.S. Also, is there a migration doc for versions 2 → 3 ?

**Comment by KostyaTretyak** [comment]
1. You need migrate to Angular 14 typed forms.
2. There no doc for migration from 2 to 3 version.

**Comment by iliakan** [comment]
Any hints on how to migrate? Just replace import to angular from @ng-stack/forms, or there are some tweaks? =)

**Comment by KostyaTretyak** [comment]
The plan is as follows:
1. Read the Angular v14 documentation.
2. Rewrite your project accordingly.

=)

**Comment by iliakan** [comment]
Very helpful. Thank you!
