### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by iliakan** [KostyaTretyak/ng-stack#114]
Is angular 15 support a pure matter of updating deps?

**Comment by KostyaTretyak** [comment]
No.

**Comment by iliakan** [comment]
May I wonder, are there any plans to support Angular 15?

P.S. Migrating the project to Angular 15, and been using your module, that's why.

**Comment by KostyaTretyak** [comment]
No, if it ever happens, it won't be soon.

**Comment by iliakan** [comment]
I understand, is there a lot to do to support it? Maybe I could just fix it? 

What's the problem, if I may ask?

**Comment by KostyaTretyak** [comment]
I switched my focus to development [Ditsmod](https://github.com/ditsmod/ditsmod) and haven't been following Angular development for a couple of years now. Maybe I'll even archive this repository.
