### ISSUE TITLE
Support for Angular v15

### ISSUE THREAD

**Issue by diogogasparr** [KostyaTretyak/ng-stack#115]
I'd like to request an update to the ng-stack library that adds support for Angular v15, ensuring that the dependencies in package.json are compatible with Angular v15.

**Comment by arslanali143** [comment]
I'd like to request an update to the ng-stack library that adds support for Angular v15, ensuring that the dependencies in package.json are compatible with Angular v1.5.

**Comment by KostyaTretyak** [comment]
Hi, @arslanali143. I'm glad you're using `@ng-stack/forms`, but it's probably time to migrate to the native version of `@angular/forms` v15, which already has partial support for strongly typed reactive forms.
