### ISSUE TITLE
newline gets removed

### ISSUE THREAD

**Issue by smoebody** [KostyaTretyak/ng-stack#23]
Hi there, I have an issue regarding newlines. Appearently they do not make it into the `value`-property of the FormControl. Would you just have a look: 

https://stackblitz.com/edit/angular-bvs5ye

Nice work btw.

**Comment by KostyaTretyak** [comment]
@smoebody, use `propValueAccessor` like this:

```html
<div contenteditable="true" propValueAccessor="innerText" [formControl]="control"></div>

<pre>
content:
========
{{content}}
</pre>
```

But see
- [Difference between textContent vs innerText](https://stackoverflow.com/q/35213147/1716560)
- and [Add linebreak to textContent or innerText only - in Chrome](https://stackoverflow.com/q/9330671/1716560)

**Comment by smoebody** [comment]
Ah, i thought i tried that param. Appearently I had a bug in my code. Sorry for bothering you.

Thanks a lot.
