### ISSUE TITLE
fg.hasError('minlength', 'name') error

### ISSUE THREAD

**Issue by bl9l** [KostyaTretyak/ng-stack#52]
When i am trying to check a formControl for a 'minlength' error, i am getting this lint error

![image](https://user-images.githubusercontent.com/46722973/61626983-1cd15c80-ac98-11e9-9c4c-beae8223ff8c.png)

I guess it should be 'minLength', but in this case it does not work.

**Comment by KostyaTretyak** [comment]
Could you provide more of your code? Did you passed your <a href="https://github.com/KostyaTretyak/ng-stack/tree/master/projects/forms#typed-validations">validation model</a> as the second parameter for the `_formGroup`?

**Comment by bl9l** [comment]
I did.

```typescript
import {FormControl, FormGroup, Validators} from '@ng-stack/forms';


_formGroup: FormGroup<RegisterModel> = new FormGroup({
    name: new FormControl<string>('', [Validators.required]),
    phone: new FormControl<string>('', [Validators.required]),
    username: new FormControl<string>('', [Validators.required, Validators.email]),
    password: new FormControl<string>('', [Validators.required, Validators.minLength(6)]),
  });
```

**Comment by bl9l** [comment]
Also for now I am using this solution.

```typescript
  _checkPasswordMinLength() {
    return this._formGroup.hasError('minlength' as any, 'password');
  }
```
![image](https://user-images.githubusercontent.com/46722973/61686318-b2242d80-ad38-11e9-8102-d55312af3c35.png)

**Comment by KostyaTretyak** [comment]
So, why you need `minlength` error name (not `minLength`)?

**Comment by bl9l** [comment]
Because, if I use minLength, the error check does not work.

**Comment by bl9l** [comment]
And mat-error, does not apear

**Comment by KostyaTretyak** [comment]
It looks like it's a bug. Try quick fix:

```ts
class MyValidatorsModel extends ValidatorsModel {
  minlength: { minlength: { requiredLength: number; actualLength: number } };
  maxlength: { requiredLength: number; actualLength: number };
}

const _formGroup: FormGroup<RegisterModel, MyValidatorsModel> = new FormGroup({
    name: new FormControl('', [Validators.required]),
    phone: new FormControl('', [Validators.required]),
    username: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(6)]),
  });
```

**Comment by bl9l** [comment]
The validation error has gone. But I got another one
![image](https://user-images.githubusercontent.com/46722973/61700313-f1ad4280-ad55-11e9-93fb-616ce2416787.png)

**Comment by KostyaTretyak** [comment]
Богдан, ви зможете читати українською мої коментарі?

**Comment by bl9l** [comment]
да

**Comment by KostyaTretyak** [comment]
Ок, я видалив свою підказку із `MyValidatorsModel`, оскільки в такому разі досить багато що прийдеться переписувати. Вам цей варіант краще не застосовувати.

Я вже досить давно займався цим модулем і позабував що і як тут працює, тому мені потрібно деякий час для виправлення цього багу.

P.S. Ноги у нього ростуть звідси https://github.com/angular/angular/issues/28721

**Comment by bl9l** [comment]
фикс раеботает, если расширить валидарор вот так
```typescript
class MyValidatorsModel extends ValidatorsModel {
  minlength: {
    requiredLength: number;
    actualLength: number;
  };
}


_formGroup = new FormGroup<RegisterModel, MyValidatorsModel>({
    name: new FormControl<string, MyValidatorsModel>('', [Validators.required]),
    phone: new FormControl<string, MyValidatorsModel>('', [Validators.required]),
    username: new FormControl<string, MyValidatorsModel>('', [Validators.required, Validators.email]),
    password: new FormControl<string, MyValidatorsModel>('', [Validators.required, Validators.minLength(6)]),
  });
```

Приходится указывать MyValidatorsModel, на кождом из FormControl.
Но этот код работает

**Comment by KostyaTretyak** [comment]
Оновлюйте:

```ts
npm i @ng-stack/forms@^1.3.3
```

Після оновлення повинно працювати і так:

```ts
_formGroup = new FormGroup<RegisterModel>({
    name: new FormControl('', [Validators.required]),
    phone: new FormControl('', [Validators.required]),
    username: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(6)]),
  });
```

**Comment by bl9l** [comment]
Работает. Спасибо

**Comment by goldel777** [comment]
For anyone having this trouble you can change validation.type.toLowerCase() and compare it to hasError() (which is in lower case)..  who know why??
