### ISSUE TITLE
Guidance on how to support Date in form model

### ISSUE THREAD

**Issue by ScottyTarvan** [KostyaTretyak/ng-stack#55]
Can you please give guidance on how to support date types for forms?

let type: SomeType{
 date: Date
};

this.someForm = new FormGroup<SomeType>({
  date: new FormControl()
}) 

This is not currently supported as a typed form control? Do we use Control<T> or any for SomeType date property?

**Comment by KostyaTretyak** [comment]
Sorry, but for now type `Date` is not supported, see https://github.com/KostyaTretyak/ng-stack/issues/46

**Comment by KostyaTretyak** [comment]
@ScottyTarvan , checkout https://github.com/KostyaTretyak/ng-stack/issues/56
