### ISSUE TITLE
Allow FormControl to accept an object

### ISSUE THREAD

**Issue by ambeur** [KostyaTretyak/ng-stack#56]
> But maybe you want for FormControl to accept an object in its constructor, instead of a primitive value. What to do in this case? At this time, it is not supported. You need to use any type instead.

hi, are there any plans to implement this feature? :)

**Comment by glebmachine** [comment]
@KostyaTretyak we can help you with implementation as well

**Comment by KostyaTretyak** [comment]
@zvnt, @glebmachine are you have any idea to fix it, how?

**Comment by KostyaTretyak** [comment]
Now, with v1.4.0-beta, you can to use `Control` type:

```ts
import { FormBuilder, Control } from '@ng-stack/forms';

const fb = new FormBuilder();

// Form Model
interface Person {
  id: number;
  name: string;
  birthDate: Control<Date>; // Here should be FormControl, instead of a FormGroup
}

const form = fb.group<Person>({
  id: 123,
  name: 'John Smith',
  birthDate: new Date(1977, 6, 30),
});

const birthDate: Date = form.value.birthDate;
```
