### ISSUE TITLE
Unhandled Promise rejection: Cannot instantiate cyclic dependency! ApplicationRef

### ISSUE THREAD

**Issue by unlight** [KostyaTretyak/ng-stack#57]
Angular `^9.0.0-next.9`
```ts
ApiMockModule.forRoot(SimpleService, { passThruUnknownUrl: true, caseSensitiveSearch: false, showLog: true }),
```
![image](https://user-images.githubusercontent.com/301732/66641598-1b2a8b80-ec2c-11e9-8bda-f4842c210747.png)

**Comment by KostyaTretyak** [comment]
@unlight, can you confirm for now that the error has not disappeared? If so, when did it occur to you? Now, with angular v9.0.5, I checked for `ng serve` and` ng build` - it's work without errors.
