### ISSUE TITLE
@ng-stack/contenteditable: support array of arrays

### ISSUE THREAD

**Issue by elana-voss** [KostyaTretyak/ng-stack#58]
Using a string as the model works fine.

However, when using an array of arrays as the model, upon entering **one** character, the `contenteditable` field loses the focus immediately and no further character can be entered.

```
<td
        contenteditable="true"
        placeholder="Enter text ..."
        *ngFor="let cell of row; let colIndex = index"
        [(ngModel)]="model[rowIndex][colIndex]"
      >
</td>
```

**Comment by KostyaTretyak** [comment]
Sorry, but only now is the free time to review your issue. This problem is solved with the [trackBy](https://angular.io/api/common/NgForOf) function in the HTML template, see [example on stackblitz](https://stackblitz.com/edit/forms-issue-58)
