### ISSUE TITLE
Disabled does not work

### ISSUE THREAD

**Issue by ghost** [KostyaTretyak/ng-stack#60]
Setting control to disabled does nothing, because there is no 'disabled' attribute on HTML Elements that support contenteditable.

Instead, it should remove the `contenteditable` attr from the host

**Comment by KostyaTretyak** [comment]
@doom777 , but why just not using `contenteditable` input like this.

In your component class:

```ts
setDisable () {
  this.isContenteditable = false;
}
```

In your template:

```html
<p [contenteditable]="isContenteditable"></p>
```

**Comment by ghost** [comment]
I can. It's definitely a workaround. But still, ControlValueAccessors should support disabling as part of their contract, and this library doesn't do it in a correct way.

**Comment by KostyaTretyak** [comment]
@doom777 , for now, in template driven forms `disabled="true"` works. In reactive forms you should use `this.reactiveForm.disable();` and this also works.

But, yes, it's still workaround (not works for input data via scripts). Without workaround, HTML should support `disabled="true"` state for `contenteditable` elements.

**Comment by ghost** [comment]
>In reactive forms you should use this.reactiveForm.disable(); and this also works.

that's the thing, it doesn't. At least not in my test. Maybe the form doesn't accept any input, but you can still type in the contenteditable.

**Comment by KostyaTretyak** [comment]
Check out this working example.

In your component class:

```ts
reactiveForm = new FormControl();
isContenteditable = true;
// ...
  ngOnInit() {
    this.reactiveForm.disable();
  }
```

Note, here `reactiveForm` is FormControl (not FormGroup).

In your template:

```html
<p [contenteditable]="isContenteditable"  [formControl]="reactiveForm"></p>
```
