### ISSUE TITLE
Formbuild requires FormGroup on object properties

### ISSUE THREAD

**Issue by rosostolato** [KostyaTretyak/ng-stack#61]
I have the following interface:
```
export interface IScheduleForm {
  date:         Date;
  worker:       string;
  service:      string;
  location:     string;
  customer:     Profile;
}
```

and I wish to implement the form group without make inner forms, because, for example, I just want to give the date Value and do not implement the whole Date form group:
```
readonly form = this.fb.group<IScheduleForm>({
  location: [null, Validators.required],
  service: [null, Validators.required],
  worker: [null, Validators.required],
  date: [null, Validators.required],
  customer: [null, Validators.required]
});
```

![image](https://user-images.githubusercontent.com/27731641/75628397-4bf96600-5bb7-11ea-9308-f48a6a800a31.png)

Is there anything I can do so it won't throw any error?

**Comment by KostyaTretyak** [comment]
As workaround, you can use `any` type for date field:

```ts
export interface IScheduleForm {
  date:         any;
  worker:       string;
  service:      string;
  location:     string;
  customer:     Profile;
}
```

See [Automatically detect appropriate types for form controls](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/forms#automatically-detect-appropriate-types-for-form-controls), https://github.com/KostyaTretyak/ng-stack/issues/56 and https://github.com/KostyaTretyak/ng-stack/issues/46

**Comment by KostyaTretyak** [comment]
Now, with v1.4.0-beta you can to use `Control` type:

```ts
import { Control } from '@ng-stack/forms';

export interface IScheduleForm {
  date: Control<Date>;
  worker: string;
  service: string;
  location: string;
  customer: Profile;
}
```

You can leave your comments in https://github.com/KostyaTretyak/ng-stack/issues/56
