### ISSUE TITLE
[question] recomendation for single route api?

### ISSUE THREAD

**Issue by freed00m** [KostyaTretyak/ng-stack#63]
Hi,

As I have multiple services I want to have multiple fake mock-api endpoints for each. 

Problem is all my requests goes tovards single route endpoint (the `/api/jsonrpc`). Our live servers decides which method you want to call from the POST body key "method".

I had one idea of using httpInterceptor that would modify the endpoint for each method and injects extra route to something like `/api/jsonrpc/${call_method}` and leave the mock-api to pick up from there. Don't know if it will work well.

**The question** is if the mock-api would benefit from having an option to "route" request from some other conditions then just` getRoutes(): [{ path: "" }] `

Something like 

```Typescript
export interface ApiMockReqBodyRoute extends ApiMockRoute {
    reqBodyKey: string; // I always have a requestBody key "method"
    reqBodyKeyValue: string; // and the method varies e.g. "Api.Login", "Api.Ping" ... so on
}
```

It would do some magic with looping Object.keys to find and compare.

Current interceptor 
```Typescript
import { HttpEvent, HttpHandler, HttpRequest } from '@angular/common/http'
import { Injectable } from '@angular/core'
import { Observable } from 'rxjs'

@Injectable({
  providedIn: 'root',
})
export class DemoRouteInterceptor {
  constructor() {}
  intercept(
    req: HttpRequest<unknown>,
    next: HttpHandler,
  ): Observable<HttpEvent<unknown>> {
    if (req.method !== 'POST' || (req.body as any).jsonrpc !== '2.0') {
      return next.handle(req)
    }
    const json_rpc_method = (req.body as any).method
    const demoized_url = `${req.url}/${json_rpc_method}`
    const demoizedReq = req.clone({ url: demoized_url })
    return next.handle(demoizedReq)
  }
}

```

**Comment by KostyaTretyak** [comment]
How did you solve this problem with `angular-in-memory-web-api`?

**Comment by freed00m** [comment]
I think I had something similar with the interceptor. Felt wrong so I ditched it and wrote fake api in python, but I love the idea to have the fak api in the browser :)

**Comment by KostyaTretyak** [comment]
As I understand it:

1. Your angular app always sends `POST` requests to the server. Yes?
1. In request body you have `method` property. Yes?
1. You want the route to be matched not only by `path`, but also by additional conditions. Yes?

**Comment by freed00m** [comment]
> As I understand it:
> 
> 1. Your angular app always sends `POST` requests to the server. Yes?

Yes, in production. For demo configuration fake it.

> 1. In request body you have `method` property. Yes?

Yes, by  jsonrpc spec it shall have method.

> 1. You want the route to be matched not only by `path`, but also by additional conditions. Yes?

Yes you understand me correctly.

**Comment by KostyaTretyak** [comment]
Why are you avoiding the single route? In your case it's more simple way then additional interceptor.

For example:

```ts
import { ApiMockService, ApiMockDataCallback, ApiMockRootRoute, ApiMockResponseCallback } from '@ng-stack/api-mock';

export class SingleService implements ApiMockService {
  getRoutes(): ApiMockRootRoute[] {
    return [
      {
        path: 'api/jsonrpc',
        dataCallback: this.getDataCallback(),
        responseCallback: this.getResponseCallback()
      },
    ];
  }

  private getDataCallback(): ApiMockDataCallback<any[]> {
    return ({ reqBody, items }) => {
      if (reqBody.method == 'GET') {
        return [
          { id: 1, name: 'Windstorm' },
          { id: 2, name: 'Bombasto' },
          { id: 3, name: 'Magneta' },
          { id: 4, name: 'Tornado' },
        ];
      } else if (reqBody.method == 'POST') {
        // Work with mutable `items`
        items.push({one: 1});
      } else {
        return items;
      }
    };
  }

  private getResponseCallback(): ApiMockResponseCallback {
    return ({ reqBody, resBody }) => {
      // Work with any conditional, if you need it.
      return resBody;
    };
  }
}
```

**Comment by freed00m** [comment]
Yes I know I could have a giant if else or switch case inside one service.

But I like the having one proxyMock service and then more code splitting.

Very ugly single method approach
```TypeScript

  private postCallback(): ApiMockResponseCallback<any> {
    return ({ httpMethod, reqBody }) => {
      const jsonrpc_head = {
        id: reqBody.id,
        jsorpc: '2.0',
      }

      const jsonrpc_method = reqBody.method
      let jsonrpc_resBody = undefined

      switch (jsonrpc_method) {
        case 'Api.Ping':
          jsonrpc_resBody = {
            token: '+0H5F53awXj6H+70V+n1zCRNzfE=',
          }
          break
        case 'Api.Login':
          jsonrpc_resBody = {
            token: '+0H5F53awXj6H+70V+n1zCRNzfE=',
          }
          break
          // AND so on
          //    and on
      }

      const response = {
        ...jsonrpc_head,
        result: jsonrpc_resBody,
      }

      return response
    }
  }
```

**Comment by KostyaTretyak** [comment]
But you can use this `SingleService` as proxy service. For example (see on constructor):

```ts
export class SingleService implements ApiMockService {
  constructor(private mock1: Mock1, private mock2: Mock2, private mock3: Mock3) { }

  getRoutes(): ApiMockRootRoute[] {
    return [
      {
        path: 'api/jsonrpc',
        dataCallback: this.getDataCallback(),
        responseCallback: this.getResponseCallback()
      },
    ];
  }

  private getDataCallback(): ApiMockDataCallback<any[]> {
    return (opts) => {
      const { reqBody, items } = opts;

      if (reqBody.method == 'GET') {
        return this.mock1(opts);
      } else if (reqBody.method == 'POST') {
        // Work with mutable `items`
        items.push({ one: 1 });
        return this.mock2(opts);
      } else {
        return items;
      }
    };
  }

  private getResponseCallback(): ApiMockResponseCallback {
    return (opts) => {
      // Work with any conditional, if you need it.
      return this.mock3(opts);
    };
  }
}
```

**Comment by freed00m** [comment]
Hmm, yes you are right.  :) Not elegant imho but It would do its job well. I might draft my functionally in a future and do PR if it turns out to not have performance hit and I'll be able to understand the core.

**Comment by KostyaTretyak** [comment]
Yes, and my example above may not work, the correct path is: `api/jsonrpc/:fakeId` or just `api/:fakeId`.
