### ISSUE TITLE
create FormGroup with field of array type

### ISSUE THREAD

**Issue by gabomgp4** [KostyaTretyak/ng-stack#64]
I want to create a FormGroup with a field that has array type:

```javascript
interface Data {
  buyer: string;
  action: Control<string[]>;
}

const fb = new FormBuilder();
const filter = fb.Group({
  buyer: '',
  action: new Array<string>()
})
```

The problem is typescript says that field action is of type string, and not string[], so the asigment is invalid. So, is there a way to use the field action as a FormControl with values of type string[]?

**Comment by KostyaTretyak** [comment]
As described in the [docs](https://angular.io/guide/reactive-forms#creating-dynamic-forms), you need to use `fb.array()` method:

```ts
interface Data {
  buyer: string;
  action: Control<string[]>;
}

const fb = new FormBuilder();
const filter = fb.group<Data>({
  buyer: '',
  action: fb.array([
    fb.control('')
  ]),
});
```

**Comment by gabomgp4** [comment]
Thanks very much for the response. In the docs, says "FormArray is an alternative to FormGroup for managing any number of unnamed controls."

I dont want to create a array of controls, i want to create one control with the value of type array. It's a control that allow the user to select many option from a list (MultiSelect), and him value is a array with the selected options really.

So, in this scenario, is posible to get strong typing with this library?

**Comment by KostyaTretyak** [comment]
If you can create your form using `@angular/forms`, it will be easy for you to rewrite it using `@ng-stack/forms`.

**Comment by KostyaTretyak** [comment]
I'm sorry, I looked through this issue very quickly yesterday and didn't see that there really is a bug. I hope to quickly fix it. Then the working version should be as follows:
```ts
interface Data {
  buyer: string;
  action: Control<string[]>;
}

const fb = new FormBuilder();
const filter = fb.group<Data>({
  buyer: '',
  action: [['one', 'two']],
});
```
As you can see, the `action` field must be an array in an array. This should be done, because if you pass it by an array, `FormBuilder` will treat it as this signature: `[someValue, SomeValidator]`

**Comment by gabomgp4** [comment]
Perfect, thanks you  very much. I'll upgrade and fix my code.

**Comment by Klaster1** [comment]
I had exactly the same issue (even the form was for a filter too), thanks for fixing it so fast 👍 Here's a simple type to wrap existing type keys into `Control`s: `type WrapControls<T> = {[K in keyof T]: T[K] extends object ? Control<T[K]> : T[K]}`.
