### ISSUE TITLE
Accessing headers in ApiMock callbacks not possible.

### ISSUE THREAD

**Issue by freed00m** [KostyaTretyak/ng-stack#65]
Hi,

Looking through the entire ApiMockResponseCallback interface, there seems to be no request headers.

I see they are that they are being logged:
```JSON
req: POST http://localhost:4200/api/jsonrpc ...................... ng-stack-api-mock.js:1309:16
{
  "headers": {
    "X-Auth-Token": "+DEMO+rkgdnja5wc3cen55le2y9="
  },
  "body": {
    "id": 1,
    "jsonrpc": "2.0",
    "method": "Api.Ping"
  }
}
```

but see inside console.login all parameters `opts: ApiMockResponseCallbackOptions<any, any>`

gives no information about the mentioned headers
```JSON
{
  "items": [],
  "itemId": "",
  "httpMethod": "POST",
  "parents": [],
  "queryParams": {},
  "reqBody": {
    "id": 1,
    "jsonrpc": "2.0",
    "method": "Api.Ping"
  }
}
```

```TypeScript
@Injectable()
export class ApiMockProxyService implements ApiMockService {
  constructor(private loginService: LoginService) {}

  getRoutes(): ApiMockRootRoute[] {
    return [
      {
        host: new URL(window.location.href).origin,
        path: `api/jsonrpc`,
        responseCallback: this.responseCallback(),
      },
    ]
  }

  responseCallback(): ApiMockResponseCallback {
    return (opts: ApiMockResponseCallbackOptions<any, any>) => {
      switch (opts.reqBody.method) {
        case 'Api.Ping':
          console.log(opts)
   .
   .
   .
```

Would it make sense to have the headers inside the ApiMockResponseCallbackOptions as well??

**Comment by KostyaTretyak** [comment]
Hi.
After your last issue here, I updated docs. See [responseCallback](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/api-mock#responsecallback).

From this callback you can return `HttpResponse` or `HttpErrorResponse`.

**Comment by freed00m** [comment]
I already sometimes use returning HttpResponse or HttpErrorResponse,

this wont help me to access and check the X Auth Token I send via request, am I correct?

**Comment by freed00m** [comment]
Let say having api that has different codes for status code coresponding some missing headers. 

```TypeScript
      return new HttpResponse({
        url: 'api/login',
        status: 400, // Would return some other status if X auth would be there
        statusText: 'Permission denied',
        headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
        body: {
          id: reqBody.id,
          jsonrpc: '2.0',
          error: { code: 100, message: 'Login Failed' },
        },
      })

```

**Comment by KostyaTretyak** [comment]
Oh, I'm sorry. You need request headers, no response headers, now I see.

Maybe instead of `reqBody`, it's better to pass the request completely. Need to think.

**Comment by KostyaTretyak** [comment]
Try upgrade to `@ng-stack/api-mock` v1.2.0 and check `reqHeaders` for the callbacks.
