### ISSUE TITLE
[question] How to debug if mock-api used?

### ISSUE THREAD

**Issue by freed00m** [KostyaTretyak/ng-stack#66]
Hi,

I just notice that when I use the fake-api the debugging becomes impossible.

See my two screenshots
This first one is without including the ApiMockModule
![2020-04-14 10_41_41-Greenshot](https://user-images.githubusercontent.com/9461698/79205250-f4991780-7e3d-11ea-8050-302f77776d9a.png)

And this is when it is used.
![2020-04-14 10_47_03-Greenshot](https://user-images.githubusercontent.com/9461698/79205284-0084d980-7e3e-11ea-97b4-40d5c482d299.png)

I am not sure if it happens on your end as well, it happens in all over the stack, variables are "not available".

Using a `debugger` keyword fails, as it never triggers anywhere.

Why?

**Comment by KostyaTretyak** [comment]
`@ng-stack/api-mock` is a module that uses the HTTP interseptor in its work, and this interseptor works the most recent. In the screenshots above, you debug variables before the mentioned interceptors start working. This is in theory, of course.

You can start debug with setting `passThruUnknownUrl: true` and with empty routes:

```ts
export class SomeService implements ApiMockService {
  getRoutes(): ApiMockRootRoute[] {
    return [];
  }
}
```

**Comment by KostyaTretyak** [comment]
And one more. What is the short variable `n` on your screen? Is this the result of minimizing the source code?

**Comment by freed00m** [comment]
I don't know, most likely is the build optimizations( I use them in both scenarios), but they never bothered me as I could debug normally. 

I try to find more stuff.

**Comment by freed00m** [comment]
I discovered this does not happen when I wont use AOT, optimization + buildOptimization
```
              "buildOptimizer": false,
              "optimization": false,
              "aot": false,
```

I don't know what is the default configuration for `ng serve` but I am sure on of the"optimization" was killing all the debugging.

Sorry for my mistake and waste of time.
