### ISSUE TITLE
api-mock: Matching urls with query parameters eg. documents?author="Bob"

### ISSUE THREAD

**Issue by Rnd-Guy** [KostyaTretyak/ng-stack#68]
For GET queries, parameters are often sent via the url, using parameter queries, e.g youtube links are of the form youtube.com/watch?v=_________

Is it possible to have these urls match the paths before the "?" character? 
Example: `documents?author=Bob` would match the same paths that `documents` would match?

Right now, I don't need it to do anything automatically, the `queryParams` collects these parameters perfectly and I'm happy to manually filter or adjust the results myself, I just need a path to be matched so I can read it and use it.

### My example:
Right now, I've got a url that looks like `documents?author=Bob`, but it cannot match `path: "documents"` or `path: "documents/:documentId"`.

To match it, I've had to explicitly create `path: "documents?author=Bob"`. Inside here, the `queryParams` object correctly contains `{author: "Bob"}`, and I can use this inside the `responseCallback` or `dataCallback` perfectly, so that part is fine.

Unfortunately this would mean I would need `path: "documents?author=Charlie"` for example to support a different parameter value, and likewise would a new path for every other possible combination of parameters.

### Possible solution
I've stepped through the code and it looks like inside the `findRouteIndex` function, the value of the `url` parameter was `documents?author=Bob` and hence couldn't find a route that matched it (didn't check exactly what it was but this likely meant that `partUrl` was `documents?` so couldn't match `documents` or `documents/`)

https://github.com/KostyaTretyak/ng-stack/blob/7e9006c8c98a9a19bcadbcf927b4942964fbfed4/projects/api-mock/src/lib/http-backend.service.ts#L205-L216

Perhaps it may need to be stripped during the function above, or just before the function is called, eg. between line 185 and 186 below:

https://github.com/KostyaTretyak/ng-stack/blob/7e9006c8c98a9a19bcadbcf927b4942964fbfed4/projects/api-mock/src/lib/http-backend.service.ts#L180-L186

When it comes to actually doing the stripping of the url, it may be possible to use the `urlSerializer.parse` function that is already being used elsewhere in the code as shown below. This may have the added benefit of supporting the other types of url parameters that can appear (eg path/matrix parameters). I don't personally need to support these other parameters right now but might be useful to others.

https://github.com/KostyaTretyak/ng-stack/blob/7e9006c8c98a9a19bcadbcf927b4942964fbfed4/projects/api-mock/src/lib/http-backend.service.ts#L341-L347

I can try making the changes myself but would need to wait until the weekend to try.

I was using v1.1.0 of the code.

**Comment by KostyaTretyak** [comment]
Sorry, but `@ng-stack/api-mock` no more supports.
