### ISSUE TITLE
Property '[sym]' is missing in type 'Date' but required in type 'UniqToken'.

### ISSUE THREAD

**Issue by pderiy** [KostyaTretyak/ng-stack#69]
Hello,

we can't use types with 'Control<someType>' because there is an error.

```typescript
interface Person {
    id: number;
    name: string;
    birthDate: Control<Date>;
}

const a: Person = {
    birthDate: new Date(),
    id: 1,
    name: '123'
};

console.log(a);
```

![image](https://user-images.githubusercontent.com/9549383/80487407-09f16400-895d-11ea-9bcc-fcdbda422540.png)

Any suggestions or fixes?

**Comment by KostyaTretyak** [comment]
As workaround, you can to do this way:

```ts
const form = fb.group<Person>({
  id: 123,
  name: 'John Smith',
  birthDate: new Date(1977, 6, 30),
});
```

But it is obvious that you took your example from this example, it seems that something is not suitable for you. Yes?

**Comment by pderiy** [comment]
If I want to use Person model without FormGroup it shows an error.
So this model is connected strict to @ng-stack/forms

**Comment by KostyaTretyak** [comment]
How about this way:

```ts
const a: Person = {
  id: 123,
  name: 'John Smith',
  birthDate: new Date(1977, 6, 30) as Control<Date>,
};
```

**Comment by pderiy** [comment]
Casting with 'as' works. I also used it this way.
But maby there is a way to fix Control<> and avoid such casting

**Comment by KostyaTretyak** [comment]
Oh man, believe me, it's not easy or impossible to fix. Do you have any ideas how to fix it?

**Comment by KostyaTretyak** [comment]
By the way, if the form model interface comes from an external library, you can do the following:

```ts
// External Form Model
interface ExternalPerson {
  id: number;
  name: string;
  birthDate: Date;
}

const a: ExternalPerson = {
  id: 123,
  name: 'John Smith',
  birthDate: new Date(1977, 6, 30),
};

interface Person extends ExternalPerson {
  birthDate: Control<Date>;
}

const form = fb.group<Person>(a);
```

**Comment by pderiy** [comment]
also no idea how to fix it.

I was thinking about similar solution:

interface IPerson {}
class PersonModel implementes IPerson {}
class PersonFormGroupModel implements IPerson {}

but a lot of code would be produced :)
