### ISSUE TITLE
Allow null as initial form control value if the "required" validator is present

### ISSUE THREAD

**Issue by TomTomB** [KostyaTretyak/ng-stack#70]
Is there maybe a way to automaticly allow `null` as a initial value even though its not allowed inside the interface? I thought this maybe could be derived from a  `required` validator being preset on the form control. 
This problem only occures if typescript is running in strict mode.

Currently I am using the following workaround:

```typescript
interface FormModel {
    name: string;
}
```

```typescript
nullVal: any = null;

constructor(private fb: FormBuilder) {}

createForm(name = null) {
    return this.fb.group<FormModel>({
      name: [name || this.nullVal, [Validators.required]],
    });
}
```

**Comment by KostyaTretyak** [comment]
What about this way?

```ts
interface FormModel {
  name: string | null;
}
```

**Comment by TomTomB** [comment]
Since I am using those models directly inside my app, I would need to add unnecessary null checks everywhere. An other option would be to have an explicit form interface e,g,:

```typescript
// Used only by the form
interface UserFormModel {
  name: string | null;
}

// Used everywhere else inside the app
interface UserModel {
  name: string;
}
``` 
This way I would need to duplicate all my interfaces and cast the return value of `this.form.value` to `UserModel` since it returns a `UserFormModel `. So not that ideal of a solution.

**Comment by KostyaTretyak** [comment]
`ng-stack/forms` only follows the rules you set through the TypeScript settings. The difficulties you have described are a fee for using strict mode.
