### ISSUE TITLE
Nested FormGroup with FormArray type error

### ISSUE THREAD

**Issue by ArielGueta** [KostyaTretyak/ng-stack#71]
I have the following code:

```ts
type MyType = { someKey: string[], group: { someNestedKey: string[] } }

new FormGroup<MyType>({
   someKey: new FormArray([]),
   group: new FormGroup({
      someNestedKey: new FormArray([]) <===== FormControl
    })
});
```

The issue that it infers `someNestedKey` as `FormControl`.

**Comment by KostyaTretyak** [comment]
Yes, it's known issue with TypeScript, see [bug(generics): errors of inferring types for an array](https://github.com/microsoft/TypeScript/issues/30207)

As workaround, you can:

```ts
import { FormGroup, FormArray } from '@ng-stack/forms';

interface SomeNestedArr {
  someNestedKey: string[];
}

interface MyType {
  someKey: string[];
  group: SomeNestedArr;
}

const form = new FormGroup<MyType>({
  someKey: new FormArray([]),
  group: new FormGroup<SomeNestedArr>({
    someNestedKey: new FormArray([]),
  }),
});
```

**Comment by ArielGueta** [comment]
Thanks, but I see that it's not just that. Take this example:
```ts
    type MyType = { someKey: string[], group: { a: string } }

    new FormGroup<MyType>({
      someKey: new FormArray([]),
      group: new FormGroup({
        b: new FormControl(),
        a: new FormControl()
      })
    });
```

It doesn't give me a type error on the `b` key.

**Comment by KostyaTretyak** [comment]
TypeScript cannot correctly infer data type only for `FormArray`:

```ts
const formGroup1 = new FormGroup({ prop: new FormControl('') }); // OK
const formGroup2 = new FormGroup({ prop: new FormGroup({}) }); // OK
const formGroup3 = new FormGroup({ prop: new FormArray([]) }); // Error
```

So it looks like this is exactly what [this issue](https://github.com/microsoft/TypeScript/issues/30207) is about.

**Comment by ArielGueta** [comment]
But I'm not talking about a FormArray. In the following example:

```ts
type MyType = { someKey: string, group: { a: string } }
    new FormGroup<MyType>({
      someKey: new FormControl(),
      group: new FormGroup({
        b: new FormControl(),
        a: new FormControl()
      })
    });
```

I expect TS to throw an error that property `b` doesn't exist on type `MyType['group']`.

**Comment by KostyaTretyak** [comment]
Oh, yes, this is another example of same issue with TypeScript. The nested `FormGroup` has no data type hints for the generic, and TypeScript tries to infer it based on the context of use.

If you remove `a` property, TypeScript will throw an error, but at the same time, do not throw errors if there are extra properties. It's all about [TypeScript design limitation](https://github.com/microsoft/TypeScript/issues/30207#issuecomment-469479122)

As you can see in the source code, constructor of `FormGroup` only accepts a type that has properties taken from the model:

https://github.com/KostyaTretyak/ng-stack/blob/d4ec1ba5abbcb069c583137cf24b312ac94c1f09/projects/forms/src/lib/form-group.ts#L38

Where `T` this is a model type.

For now, I don't know of any other ways to fix this issue other than making data type hints:

```ts
type MyType = { someKey: string; group: { a: string } };

const form = new FormGroup<MyType>({
  someKey: new FormControl(),
  group: new FormGroup<{ a: string }>({
    b: new FormControl(),
    a: new FormControl()
  })
});
```

**Comment by KostyaTretyak** [comment]
I just added examples to the [Known issues with data type infer](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/forms#known-issues-with-data-type-infer) section.
