### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NetanelBasal** [KostyaTretyak/ng-stack#72]
Hey, what's up? We recently wrote a library that takes a similar approach to yours and supports types. Also, we've added reactive queries and more useful methods. I happen to come across your library, and I think that you can add value to the library. Is joining us is something that could interest you?

**Comment by KostyaTretyak** [comment]
Are you talk about @ng-stack/forms? If - yes, you can describe your library in [Reactive forms are not strongly typed](https://github.com/angular/angular/issues/13721)
