### ISSUE TITLE
File input value erased during `change` event

### ISSUE THREAD

**Issue by bcallaghan-et** [KostyaTretyak/ng-stack#74]
File inputs automatically have an accompanying label that reads "No file chosen". When selecting a single file, the label changes to the name of the file. When selecting multiple files, the label changes to the number of files selected. This is incredibly useful behavior as it provides confirmation to the user that their files were selected. This library forcefully removes the files from the native HTML element at the end of every `change` event. The result is that the label always reads "No file chosen", even after the user has selected files. The files are still validated and counted as part of the form, but the user has lost that confirmation, and it appears to them that the field is not working at all.

Please remove this instruction, as it only harms user experience. If for some reason it can't be removed, please add an option to preserve the field's native value.

The offending line is
https://github.com/KostyaTretyak/ng-stack/blob/ee7cd79590f7aee49ad471b327d6303b20c54f71/projects/forms/src/lib/input-file.directive.ts#L37

**Comment by KostyaTretyak** [comment]
Without this feature, if you need to re-select the same file after changing it in the file system (for example, reduce the size of the avatar image), you will not be able to see the changes. This is how the browser cache works.

As a workaround, you can do the following:

```html
<label for="files" class="here-class-for-your-button">Select Image</label>
<input ... style="display:none" id="files"/>
```

So you can change the output text to the desired one. Although, soon I'm going to add an option so you can work with the default behavior `input[type=file]`. I will let you know about this in this issue.

**Comment by KostyaTretyak** [comment]
Now you can upgrade to `v2.1.0` and use [`preserveValue` option](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/forms#preserveValue-option)
