### ISSUE TITLE
Pass input `multiple` into the native element

### ISSUE THREAD

**Issue by bcallaghan-et** [KostyaTretyak/ng-stack#75]
The input attribute `multiple` is much simpler to use than the HTML native attribute. However, setting `[multiple]="true"` does not actually allow the user to select multiple files. All the input setting does currently is change the name of the form field in the final result. Please use the value of `multiple` to add or remove the native attribute to the underlying input.

https://github.com/KostyaTretyak/ng-stack/blob/ee7cd79590f7aee49ad471b327d6303b20c54f71/projects/forms/src/lib/input-file.directive.ts#L12

**Comment by KostyaTretyak** [comment]
In v2.1.0 this bug is fixed.

**Comment by bcallaghan-et** [comment]
@KostyaTretyak Unfortunately, this change doesn't work in all cases. Modern browsers only check for the existence of the `multiple` attribute and don't actually read its value. Thus, setting a value of `multiple="false"` still allows multiple files to be selected. The only way to disable this behavior is to remove the attribute entirely.

**Comment by bcallaghan-et** [comment]
@KostyaTretyak After some more testing, I found that this change also prevents my previous workaround of setting the attribute manually no longer works, as the input file directive will overwrite my value. I was previously using `[attr.multiple]="allowMultiple ? '' : null"` to set or remove the attribute as appropriate.

**Comment by KostyaTretyak** [comment]
Ok, now I see. As workaround you can set `multiple=""` or `multiple="null"`. Now I will try to fix it.
