### ISSUE TITLE
NgStackFormsModule has not been processed correctly by ngcc.

### ISSUE THREAD

**Issue by keygjones** [KostyaTretyak/ng-stack#81]
Hi,

Im trying to create a stackblitz example of an error we are getting by extending the Formgroup of ng-stack forms ... , seems like the ivy compiler is stuggeling with the NgStackFormsModule  ... ngcc failed to run on @ng-stack/forms@2.2.3.

https://stackblitz.com/edit/angular-ivy-formroot?file=src/app/formroot.ts

any ideas?

**Comment by KostyaTretyak** [comment]
Hi,

To create an example on stackblitz, it is better to do it on the basis of a repository from github.com. For example, I have [repo](https://github.com/KostyaTretyak/ng-stack-test-v10) with pure Angular v10.0.14 and `@ng-stack/forms` v2.2.3. And then you can just open https://stackblitz.com/github/KostyaTretyak/ng-stack-test-v10 and see result. No issue with `@ng-stack/forms`.
