### ISSUE TITLE
Custom Validators are getting passed the wrong control instance 

### ISSUE THREAD

**Issue by TomTomB** [KostyaTretyak/ng-stack#82]
Checking for `foo instanceof FormControl` inside a custom validaor returns false if the `FormControl` is imported from `@ng-stack/forms`. If it's imported from `@angular/forms` this will return true. 

To reproduce this issue just use the following validator inside your form:
```typescript
import { AbstractControl, FormControl as FormControlNative } from '@angular/forms';
import { FormControl, ValidatorFn } from '@ng-stack/forms';

export const fooValidator: ValidatorFn = (fc: AbstractControl) => {

  console.log(fc instanceof FormControl); // will be false
  console.log(fc instanceof FormControlNative); // will be true
  
  if (!(fc instanceof FormControl) && !(fc instanceof FormControlNative)) {
    return null;
  }

  return (fc.value as string).indexOf('foo') ? null : { foo: true };
};
```

**Comment by KostyaTretyak** [comment]
If you create form control like this:

```ts
import { FormControl } from '@ng-stack/forms';

// ... Inside your component
testFormControl = new FormControl();
// ...
```

You will get "true, true", but if you create form control via `FormBuilder` then "false, true" and it's OK.

`@ng-stack/forms` almost does not change the runtime behavior of the native module `@angular/forms` because its job is to provide types.

**Comment by TomTomB** [comment]
I think that's kind of inconsistent. If I use the `FormBuilder` provided by `@ng-stack/forms` I would expect it to create a form using the  `@ng-stack/forms`  classes and not `@angular/forms` ones. I would like to ban any imports from `@angular/forms` inside my projects via TS Lint rule, but this behaviour makes it pretty hard. As long as I dont add `tslint:disable-next-line: import-blacklist` comments to every `@angular/forms`  import.

**Comment by KostyaTretyak** [comment]
Hmm. I uses VS Code and it ask me from where I want to import symbols. The first is import from `@angular/forms`, and the second from `@ng-stack/forms`. Not much work.

Maybe your IDE can also be configured for this in some way?

**Comment by KostyaTretyak** [comment]
By the way, tslint should probably be able to see the TypeScript type, not the JavaScript type. I mean, `FormBuilder` returns instance of `FormControl` with a type that goes with `@ng-stack/forms`. So I guess you can create a rule that forbids TypeScript type instead of JavaScript `instanceof`. Although, this is my theory, in practice I don't often write rules for tslint.
