### ISSUE TITLE
contenteditable: output ignoring new lines

### ISSUE THREAD

**Issue by SDVII** [KostyaTretyak/ng-stack#83]
First of all, thank you for your great work!

It seems that the output of the `contenteditable` directive is ignoring new lines. Is there a property or solution to avoid this?

Thank you for your time.

**Comment by KostyaTretyak** [comment]
Hi. You can use [propValueAccessor](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/contenteditable#propvalueaccessor). Try `propValueAccessor="innerHTML"` or `propValueAccessor="innerText"`. See [stackoverflow](https://stackoverflow.com/q/9330671/1716560)

**Comment by SDVII** [comment]
It's working perfectly now! Thanks for the rapid response!
