### ISSUE TITLE
contenteditable: Give a specific directive identifier for the module

### ISSUE THREAD

**Issue by SDVII** [KostyaTretyak/ng-stack#84]
Hello,

I've been using this module for a while and it's amazing! However, if there is a certain directive that also can be used with `contenteditable` and has it's own value accessor, Angular will throw a `More than one custom value accessor matches form control with unspecified name attribute` error. 

Is it possible to change the identifier from [contenteditable][formControl][..] to something like [stack-contenteditable]? Or is it possible to override it somehow?

I tried using `[contenteditable]=false`, but it didn't work.
Also, the same component is using both modules so I cannot selectively import the modules.

Thank you for your time.

**Comment by KostyaTretyak** [comment]
Hi @SDVII. Do you use two separate modules that have the same selectors? Do I understand you correctly?

**Comment by SDVII** [comment]
Let me try and explain it with a case scenario.

Let's say I have a bug report page with two inputs:
1. A resizable content editable `DIV` in order to input something like a bug description.
2. A comment input that can be used with user mentions using `@` character.

I've created a mention directive and gave it the selector `[UserMentions]`. This directive searches a user directory and returns a styled `SPAN` on user selection. The directive can only be used with a content editable `DIV` element and has it's own value accessors defined, something like this:
```html
<div id="comment=input" UserMentinos contenteditable [formControl]="control"></div>
```

The description input will utilize this module like this:
```html
<div id="bug-description" contenteditable [formControl]="control"></div>
```

However, because this module's selectors are generic; `[contenteditable][formControl]`, both value accessors are being applied.
For scenarios like these, shouldn't the module have a more specific selector? maybe something like `[NgstackContenteditable]`. This way you can use other directive that requires `contenteditable` without using this module unless specified.

**Comment by KostyaTretyak** [comment]
> However, because this module's selectors are generic;

What this mean? Module's selectors are `string`s...

I have never encountered this. I do not understand what can change if I change the name of the selector. You do not have such a selector as my module.

But you can copy/paste [this two files](https://github.com/KostyaTretyak/ng-stack/tree/master/projects/contenteditable/src/lib), change selector and you can import from it.

**Comment by SDVII** [comment]
I am sorry for the confusion, what I meant by generic here is that they are not specific to the module. The directive has the following selectors: `[contenteditable][formControlName],[contenteditable][formControl],[contenteditable][ngModel]`.

All of the keys are either html attributes (contenteditable) or angular syntax (formControlName, formControl, ngModel) which makes it hard to disable or override in order to use another directive that has it's own value accessor.

Anyway, I was just suggesting that a unique identifier should be added in order to avoid clashes. If you don't feel that is necessary, please feel free to close this ticket.

Thanks for the quick response.
