### ISSUE TITLE
FormGroup validations model V type parameter is too restrictive. 

### ISSUE THREAD

**Issue by zegelin** [KostyaTretyak/ng-stack#86]
Fantastic library. But I've hit a bit of a stumbling block.

The validation model type parameter `V` on `FormGroup` enforces `V` on all child controls. The result of this is an entire form must use a single validation model type, rather than something different for each control and/or group. This prohibits easy composability of custom form control components.

For example:

```
interface SuperValidationErrors {
    notSuper: boolean;
}

interface CoolValidationErrors {
    notCool: boolean;
}

class SuperCool {
    super: string;
    cool: string;
}

formGroup = new FormGroup<SuperCool>({
    super: new FormControl<string, SuperValidationErrors>('', null, (control => {
        return of((control.value === 'syndrome' ? {notSuper: true} : null)).pipe(delay(1000));
    })),
    cool: new FormControl<string, CoolValidationErrors >('', null, (control => {
        return of((control.value !== 'joe' ? {notCool: true} : null)).pipe(delay(1000));
    })),
});
```

won't compile, as `FormGroup` defaults `V` to `ValidatorsModel`, which enforces `V` on all child controls.

It can be sort-of tricked to work if you specify `FormGroup<SuperCool, SuperValidationErrors | CoolValidationErrors>`. This is less than ideal though:

- the `FormGroup` type signature grows rapidly, especially if each sub-field has its own validation type. Nested FormGroups become unwieldy.
- `FormControl`s using the default validation model are no longer compatible, unless something like `SuperValidationErrors | CoolValidationErrors | ValidatorsModel` is used.
- `formGroup.controls.super.errors` now is of type `SuperValidationErrors | CoolValidationErrors`, preventing property access unless casts are used.

An example error from trying to access the validation model in the template:
```
Error: src/app/super-cool-form-control/super-cool-form-control.component.ts:40:57 - error TS2339: Property 'notCool' does not exist on type 'SuperValidationErrors | CoolValidationErrors'.
      Property 'notCool' does not exist on type 'SuperValidationErrors'.

<span *ngIf="group.controls.cool.errors.notCool">Invalid: <code>{{group.controls.cool.errors | json}}</code></span>
```

**Comment by zegelin** [comment]
I should mention that I'm new to TypeScript and Angular. Sorry if I've missed something painfully obvious.

**Comment by KostyaTretyak** [comment]
Try this:

```ts
interface SuperValidationErrors extends ValidatorsModel {
  notSuper: boolean;
}

interface CoolValidationErrors extends ValidatorsModel {
  notCool: boolean;
}

const formGroup = new FormGroup({
  super: new FormControl<string, SuperValidationErrors>('', null, (control) => {
    return of(control.value === 'syndrome' ? { notSuper: true } : null).pipe(delay(1000));
  }),
  cool: new FormControl<string, CoolValidationErrors>('', null, (control) => {
    return of(control.value !== 'joe' ? { notCool: true } : null).pipe(delay(1000));
  }),
});
```

**Comment by KostyaTretyak** [comment]
Try this:

```ts
import { FormControl, FormGroup } from '@ng-stack/forms';
import { of } from 'rxjs';
import { delay } from 'rxjs/operators';

interface SuperValidationErrors {
  notSuper: boolean;
}

interface CoolValidationErrors {
  notCool: boolean;
}

class SuperCool {
  super: string;
  cool: string;
}

const formGroup = new FormGroup<SuperCool, any>({
  super: new FormControl<string, SuperValidationErrors>('', null, (control) => {
    return of(control.value === 'syndrome' ? { notSuper: true } : null).pipe(delay(1000));
  }),
  cool: new FormControl<string, CoolValidationErrors>('', null, (control) => {
    return of(control.value !== 'joe' ? { notCool: true } : null).pipe(delay(1000));
  }),
});
```

Here fix `new FormGroup<SuperCool, any>`. If you need different validators, just specify `any` in the parent validator model.

**Comment by KostyaTretyak** [comment]
You can reopen this issue if the problem is not resolved.
