### ISSUE TITLE
Wrong peerDependency in api-mock, please bump the semver

### ISSUE THREAD

**Issue by freed00m** [KostyaTretyak/ng-stack#89]
I know you fixed the Angular 11 dependency, but the semantic versioning hasn't change, so npmjs.com still contains the unpatched version that has wrong version.

After adding your module
```
 /frontend/node_modules/@ng-stack/api-mock $ cat package.json | grep peer -A 1
  "peerDependencies": {
    "@angular/core": ">=4.3.6 <11.0.0",
 frontend/node_modules/@ng-stack/api-mock $ cat package.json | grep version
  "version": "1.3.0",
```

**Comment by freed00m** [comment]
Is there a reason for not bumping the semver? 

The readme tells users to `npm i -D @ng-stack/api-mock` but that will isntall the year old version from https://www.npmjs.com/package/@ng-stack/api-mock

**Comment by KostyaTretyak** [comment]
@freed00m, sorry for the delay in resolving this issue. I'm trying to migrate the whole project to TypeScript "strict mode" but I had some difficulty with `@ng-stack/api-mock`. I will try to do it in the next couple of weeks.

**Comment by KostyaTretyak** [comment]
Try upgrade `@ng-stack/api-mock` to v1.4.0
